===================================================================================================
2022/03/02

Traceback (most recent call last):
  File "C:\Users\81704\mysite\mysite\manage.py", line 22, in <module>
    main()
  File "C:\Users\81704\mysite\mysite\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\81704\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\81704\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\81704\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\81704\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)        
  File "C:\Users\81704\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\81704\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\management\commands\migrate.py", line 95, in handle
    executor.loader.check_consistent_history(connection)
  File "C:\Users\81704\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\migrations\loader.py", line 306, in check_consistent_history    raise InconsistentMigrationHistory(
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration admin.0001_initial is applied before its dependency accounts.0001_initial on database 'default'.